EPII/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path("search/", views.PostSearch, name="search"),
    path("create/", views.PostCreat, name="create"),
    path("<int:post_id>/", views.PostDetail, name="detail"),
    path("update/<int:post_id>/", views.PostUpdate, name="update"),
    path("delete/<int:post_id>/", views.PostDelete, name="delete"),
    path("<int:post_id>/comentario/", views.create_comentario, name="comentario"),
    path("lists/", views.ListListView.as_view(), name="lists"),
    path("lists/create", views.ListCreateView.as_view(), name="create-list"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} InvesteProspera - Educação Financeira
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                    <li> Logado com {{ user.username }} </li>
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
                <li><a href="{% url 'app:index' %}">Postagens</a></li>
                <li><a href="{% url 'app:lists' %}">Favoritos da Comunidade</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023 AleUni</small>
        </p>
    </footer>
</body>

</html>