EPII/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('accounts/', include('accounts.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path("search/", views.PostSearch, name="search"),
    path("create/", views.PostCreat, name="create"),
    path("<int:post_id>/", views.PostDetail, name="detail"),
    path("update/<int:post_id>/", views.PostUpdate, name="update"),
    path("delete/<int:post_id>/", views.PostDelete, name="delete"),
    path("<int:post_id>/comentario/", views.create_comentario, name="comentario"),
    path("lists/", views.ListListView.as_view(), name="lists"),
    path("lists/create", views.ListCreateView.as_view(), name="create-list"),
]

app/models.py
from django.db import models
from django.conf import settings

# Create your models here.



class Postagem(models.Model):
    name = models.CharField(max_length=255)
    categoria = models.CharField(max_length=255)
    image_url = models.URLField(max_length=200, null=True)
    texto = models.CharField(max_length=3000, null=True)
    data = models.DateField(auto_now_add=True)
    def __str__(self):
        return f"{self.name}"


class Comentario(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    data = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Postagem, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField(Postagem)

    def __str__(self):
        return f"{self.name} by {self.author}"

app/templates/app/comment.html
{% extends 'base.html' %}
{% block content %}
    <h2>Comentar Artigo {{ post.name }} ({{ post.categoria }})</h2>
    <form action="{% url 'app:comentario' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Postar Comentário</button>
    </form>
    <p>
        <a href="{% url 'app:detail' post.id %}">Voltar para a página do artigo</a>
    </p>
{% endblock content %}

app/templates/app/creat_list.html
{% extends 'base.html' %}
{% block title %}
    Criar Artigo de Investimento
{% endblock title %}
{% block content %}
    <h2>Criar Lista de Artigos Favoritos</h2>
    <form action="{% url 'app:create-list' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar</button>
    </form>
{% endblock content %}

app/templates/app/create.html
{% extends 'base.html' %}
{% block title %}
    Criar Artigo
{% endblock title %}
{% block content %}
    <h2>Adicionar Artigo de Investimento</h2>
    <form action="{% url 'app:create' %}" method="post">
        {% csrf_token %}
        {{ post_form.as_p }}
        <button type="submit">Criar</button>
    </form>
{% endblock content %}

app/templates/app/delete.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'app:delete' post.id %}" method="post">
        {% csrf_token %}
        <p>Você tem certeza que deseja apagar o artigo"{{ post.name }} ({{ investment.categoria }})"?</p>
        <button type="submit">Apagar</button>
    </form>
{% endblock content %}

app/templates/app/detail.html
{% extends 'base.html' %}
{% block title %}
    <strong>{{ post.name }}</strong> (<strong>{{ post.categoria }}</strong>)
{% endblock title %}
{% block content %}
    <h2>{{ post.name }}</h2>
    <section class="dados-de-post">
        <img src="{{ post.image_url }}" alt="Foto do artigo {{ post.name }}">
        <ul>
            <li><u>Nome</u>: <strong>{{ post.name }}</strong></li>
            <li><u>Categoria</u>: <strong>{{ post.categoria }}</strong></li>
            <li><u>Data</u>: <strong>{{post.data}}</strong></li>
            <li><u>Texto</u>: {{ post.texto }}</li>
            {% if post.list_set.all %}<li><u>Incluso nas listas</u>: {{ post.list_set.all|join:", " }}</li>{% endif %}
            <li>
                <a href="{% url 'app:update' post.id %}">Editar</a>
            </li>
            <li>
                <a href="{% url 'app:delete' post.id %}">Apagar</a>
            </li>
        </ul>
    </section>
    <hr>
    <section>
        <header>
            <h3>Comentários</h3>
        </header>
        <ul>
            {% if post.comentario_set.all %}
                {% for comentario in post.comentario_set.all %}
                    <figure>
                        <blockquote>
                            "{{ comentario.text }}"
                        </blockquote>
                        <figcaption>—{{ comentario.author }}, {{comentario.data}}</figcaption>
                    </figure>
                {% endfor %}
            {% else %}
                <p>Ainda não existe nenhum comentário para este artigo.</p>
            {% endif %}
        </ul>
        <hr>
        <a href="{% url 'app:comentario' post.pk %}">
            <button>Crie seu Comentário</button>
        </a>
    </section>
{% endblock content %}

app/templates/app/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Artigos</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'app:search' %}">Buscar Artigos</a></p>
    {% if perms.app.add_post %}
        <p>Não encontrou o artigo? <a href="{% url 'app:create' %}">Adicionar Novo Artigo</a></p>
    {% endif%}
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'app:detail' post.id %}"><img src="{{ post.image_url }}"
                alt="Foto do Artigo {{ post.name}}"></a>
        <p>{{ post.name }} ({{ post.categoria }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum artigo.</p>
{% endif %}

{% if last_posts %}
<hr>
<h2>Últimos vistos</h2>
<section class="lista-de-cards">
    {% for last_post in last_posts %}
    <article class="small-card">
        <a href="{% url 'app:detail' last_posts.id %}"><img src="{{ last_post.image_url }}"
                alt="Foto do artigo {{ last_post.name}}"></a>
    </article>
    {% endfor %}
</section>
{% endif %}

{% endblock content %}

app/templates/app/lists.html
{% extends 'base.html' %}

{% block title %}
Listas
{% endblock title %}

{% block content %}
<h2>Favoritos da Comunidade</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{list.name}} (de {{ list.author }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for post in list.app.all %}
            <div class="card">
                <a href="{% url 'app:detail' post.id %}"><img src="{{ post.image_url }}"
                        alt="Foto do Artigo {{ post.name}}"></a>
                <p>{{ post.name }} ({{ post.categoria }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'app:create-list' %}"><button>Crie sua Lista</button></a>
</section>

{% endblock content %}

app/templates/app/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Artigos por Nome</h2>
<form action="{% url 'app:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.image_url }}" alt="Foto do artigo {{ post.name}}">
        <p>{{ post.name }} ({{ post.categoria }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

app/templates/app/update.html
{% extends 'base.html' %}
{% block content %}
    <h2>Atualizar Dados do Artigo {{ post.name }}</h2>
    <form method="POST" action="{% url 'app:update' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </form>
{% endblock content %}